services:
  opa-bundle:
    url: http://opa-bundle:8095  # Docker Compose 네트워크에서 opa-bundle 서비스로 접근

bundles:
  baro:
    service: opa-bundle
    resource: /opa/bundle
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 60

decision_logs:
  console: true
